name: Hello Yani

on:
  push:
    branches:
      - source

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install GitBook
      run: npm install -g gitbook-cli --registry=https://registry.npm.taobao.org

    - name: Checkout source
      uses: actions/checkout@v1
      with:
        ref: source

    - name: GitBook Install
      run: gitbook install --registry=https://registry.npm.taobao.org

    - name: Build
      run: gitbook build . docs

    - name: Publish 
      run: |
        git config --global user.email "${COMMIT_EMAIL}"
        git config --global user.name "${COMMIT_NAME}"
        git add -f docs
        git commit -m "Deploying to master from source" --quiet
        git push $REPOSITORY_PATH `git subtree split --prefix docs source`:master --force
      shell: bash

#
#    - name: Publish
#      uses: hlyani/gitbook-deploy-action@master
#      env:
#        ACCESS_TOKEN: ${{ secrets.testaction }}
#        BASE_BRANCH: source
#        BRANCH: master
#        FOLDER: docs
